import { css } from '@emotion/react'

export const customProperty = css({
  ':root': {
    '--color-gray-0': '#FFFFFF',
    '--color-gray-50': '#FAFAFA',
    '--color-gray-100': '#F5F5F5',
    '--color-gray-200': '#EEEEEE',
    '--color-gray-300': '#E0E0E0',
    '--color-gray-400': '#BDBDBD',
    '--color-gray-500': '#9E9E9E',
    '--color-gray-600': '#757575',
    '--color-gray-700': '#616161',
    '--color-gray-800': '#424242',
    '--color-gray-900': '#212121',
    '--color-brown-500': '#9D9068',
    '--color-brown-700': '#6D633E',
    '--color-brown-900': '#423915',
    '--color-background': 'var(--color-gray-100)',
    '--color-surface': 'var(--color-gray-0)',
    '--color-main': 'var(--color-brown-700)',
    '--color-main-light': 'var(--color-brown-500)',
    '--color-main-dark': 'var(--color-brown-900)',
    '--color-dark-text-disabled': 'rgba(0, 0, 0, 0.38)',
    '--color-dark-text-medium-emphasis': 'rgba(0, 0, 0, 0.6)',
    '--color-dark-text-high-emphasis': 'rgba(0, 0, 0, 0.87)',
    '--color-light-text-disabled': 'rgba(255, 255, 255, 0.38)',
    '--color-light-text-medium-emphasis': 'rgba(255, 255, 255, 0.6)',
    '--color-light-text-high-emphasis': 'rgba(255, 255, 255, 0.87)',
    '--color-text-on-surface': 'var(--color-dark-text-high-emphasis)',
    '--color-text-on-main': 'var(--color-light-text-high-emphasis)',
    '--font-size-title': '40px',
    '--font-size-headline1': '32px',
    '--font-size-headline2': '24px',
    '--font-size-subhead1': '20px',
    '--font-size-subhead2': '18px',
    '--font-size-body1': '16px',
    '--font-size-body2': '14px',
    '--font-size-body3': '12px',
    '--line-height-title': '56px',
    '--line-height-headline1': '46px',
    '--line-height-headline2': '36px',
    '--line-height-subhead1': '30px',
    '--line-height-subhead2': '28px',
    '--line-height-body1': '26px',
    '--line-height-body2': '22px',
    '--line-height-body3': '18px',
  },
  '@media (prefers-color-scheme: dark)': {
    ':root': {
      '--color-background': 'var(--color-gray-900)',
      '--color-surface': 'var(--color-gray-800)',
      '--color-main': 'var(--color-brown-700)',
      '--color-main-light': 'var(--color-brown-900)',
      '--color-main-dark': 'var(--color-brown-500)',
      '--color-text-on-surface': 'var(--color-light-text-high-emphasis)',
      '--color-text-on-main': 'var(--color-light-text-high-emphasis)',
    },
  },
})
